name: Build

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:

jobs:
  publish-npm:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 26
          registry-url: https://registry.npmjs.org/
          cache: npm
      - run: npm install -g npm@latest
      - run: npm i
      - run: npm test
      - run: npm run build --if-present
      - run: npm test
